experiment:
  name: synthetic_4cycle_10bbpc_1000m_err=0
  fastq_path: /tmp/60664159/delt-hit-benchmarks/60664159/synthetic_4cycle_10bbpc_1000m_err=0/data/synthetic_4cycle_10bbpc_1000m_err=0/synthetic_4cycle_10bbpc_1000m_err=0.fastq.gz
  save_dir: /tmp/60664159/delt-hit-benchmarks/60664159/synthetic_4cycle_10bbpc_1000m_err=0/tools/delt/synthetic_4cycle_10bbpc_1000m_err=0
  num_cores: 11
selections:
  synthetic_selection:
    operator: Codex
    date: '2026-04-24'
    group: synthetic
    target: synthetic_target
    S0: ACGTACGTAC
    ids:
    - 0
structure:
- name: S0
  type: selection
  max_error_rate: 0.0
  indels: false
- name: B0
  type: building_block
  max_error_rate: 0.0
  indels: false
- name: B1
  type: building_block
  max_error_rate: 0.0
  indels: false
- name: B2
  type: building_block
  max_error_rate: 0.0
  indels: false
- name: B3
  type: building_block
  max_error_rate: 0.0
  indels: false
- name: C0
  type: constant
  max_error_rate: 0.0
  indels: false
whitelists:
  C0:
  - codon: TTGGAACC
  S0:
  - name: synthetic_selection
    codon: NNNNNNNNACGTACGTAC
  B0:
  - index: 0
    codon: AAAAAAAA
    building_block_id: BB1_001
  - index: 1
    codon: AAAAAAAC
    building_block_id: BB1_002
  - index: 2
    codon: AAAAAAAG
    building_block_id: BB1_003
  - index: 3
    codon: AAAAAAAT
    building_block_id: BB1_004
  - index: 4
    codon: AAAAAACA
    building_block_id: BB1_005
  - index: 5
    codon: AAAAAACC
    building_block_id: BB1_006
  - index: 6
    codon: AAAAAACG
    building_block_id: BB1_007
  - index: 7
    codon: AAAAAACT
    building_block_id: BB1_008
  - index: 8
    codon: AAAAAAGA
    building_block_id: BB1_009
  - index: 9
    codon: AAAAAAGC
    building_block_id: BB1_010
  B1:
  - index: 0
    codon: AGCTACAA
    building_block_id: BB2_001
  - index: 1
    codon: AGCTACAC
    building_block_id: BB2_002
  - index: 2
    codon: AGCTACAG
    building_block_id: BB2_003
  - index: 3
    codon: AGCTACAT
    building_block_id: BB2_004
  - index: 4
    codon: AGCTACCA
    building_block_id: BB2_005
  - index: 5
    codon: AGCTACCC
    building_block_id: BB2_006
  - index: 6
    codon: AGCTACCG
    building_block_id: BB2_007
  - index: 7
    codon: AGCTACCT
    building_block_id: BB2_008
  - index: 8
    codon: AGCTACGA
    building_block_id: BB2_009
  - index: 9
    codon: AGCTACGC
    building_block_id: BB2_010
  B2:
  - index: 0
    codon: CATGAGAA
    building_block_id: BB3_001
  - index: 1
    codon: CATGAGAC
    building_block_id: BB3_002
  - index: 2
    codon: CATGAGAG
    building_block_id: BB3_003
  - index: 3
    codon: CATGAGAT
    building_block_id: BB3_004
  - index: 4
    codon: CATGAGCA
    building_block_id: BB3_005
  - index: 5
    codon: CATGAGCC
    building_block_id: BB3_006
  - index: 6
    codon: CATGAGCG
    building_block_id: BB3_007
  - index: 7
    codon: CATGAGCT
    building_block_id: BB3_008
  - index: 8
    codon: CATGAGGA
    building_block_id: BB3_009
  - index: 9
    codon: CATGAGGC
    building_block_id: BB3_010
  B3:
  - index: 0
    codon: CTCCATAA
    building_block_id: BB4_001
  - index: 1
    codon: CTCCATAC
    building_block_id: BB4_002
  - index: 2
    codon: CTCCATAG
    building_block_id: BB4_003
  - index: 3
    codon: CTCCATAT
    building_block_id: BB4_004
  - index: 4
    codon: CTCCATCA
    building_block_id: BB4_005
  - index: 5
    codon: CTCCATCC
    building_block_id: BB4_006
  - index: 6
    codon: CTCCATCG
    building_block_id: BB4_007
  - index: 7
    codon: CTCCATCT
    building_block_id: BB4_008
  - index: 8
    codon: CTCCATGA
    building_block_id: BB4_009
  - index: 9
    codon: CTCCATGC
    building_block_id: BB4_010
library:
  products: []
  educts: []
  reactions: []
  bb_edges: []
  other_edges: []
  building_blocks:
  - B0
  - B1
  - B2
  - B3
catalog:
  compounds: {}
  reactions: {}
