experiment:
  name: synthetic_2cycle_100bbpc_1000m_err=0
  fastq_path: /tmp/60664160/delt-hit-benchmarks/60664160/synthetic_2cycle_100bbpc_1000m_err=0/data/synthetic_2cycle_100bbpc_1000m_err=0/synthetic_2cycle_100bbpc_1000m_err=0.fastq.gz
  save_dir: /tmp/60664160/delt-hit-benchmarks/60664160/synthetic_2cycle_100bbpc_1000m_err=0/tools/delt/synthetic_2cycle_100bbpc_1000m_err=0
  num_cores: 11
selections:
  synthetic_selection:
    operator: Codex
    date: '2026-04-24'
    group: synthetic
    target: synthetic_target
    S0: ACGTACGTAC
    ids:
    - 0
structure:
- name: S0
  type: selection
  max_error_rate: 0.0
  indels: false
- name: B0
  type: building_block
  max_error_rate: 0.0
  indels: false
- name: B1
  type: building_block
  max_error_rate: 0.0
  indels: false
- name: C0
  type: constant
  max_error_rate: 0.0
  indels: false
whitelists:
  C0:
  - codon: TTGGAACC
  S0:
  - name: synthetic_selection
    codon: NNNNNNNNACGTACGTAC
  B0:
  - index: 0
    codon: AAAAAAAA
    building_block_id: BB1_001
  - index: 1
    codon: AAAAAAAC
    building_block_id: BB1_002
  - index: 2
    codon: AAAAAAAG
    building_block_id: BB1_003
  - index: 3
    codon: AAAAAAAT
    building_block_id: BB1_004
  - index: 4
    codon: AAAAAACA
    building_block_id: BB1_005
  - index: 5
    codon: AAAAAACC
    building_block_id: BB1_006
  - index: 6
    codon: AAAAAACG
    building_block_id: BB1_007
  - index: 7
    codon: AAAAAACT
    building_block_id: BB1_008
  - index: 8
    codon: AAAAAAGA
    building_block_id: BB1_009
  - index: 9
    codon: AAAAAAGC
    building_block_id: BB1_010
  - index: 10
    codon: AAAAAAGG
    building_block_id: BB1_011
  - index: 11
    codon: AAAAAAGT
    building_block_id: BB1_012
  - index: 12
    codon: AAAAAATA
    building_block_id: BB1_013
  - index: 13
    codon: AAAAAATC
    building_block_id: BB1_014
  - index: 14
    codon: AAAAAATG
    building_block_id: BB1_015
  - index: 15
    codon: AAAAAATT
    building_block_id: BB1_016
  - index: 16
    codon: AAAAACAA
    building_block_id: BB1_017
  - index: 17
    codon: AAAAACAC
    building_block_id: BB1_018
  - index: 18
    codon: AAAAACAG
    building_block_id: BB1_019
  - index: 19
    codon: AAAAACAT
    building_block_id: BB1_020
  - index: 20
    codon: AAAAACCA
    building_block_id: BB1_021
  - index: 21
    codon: AAAAACCC
    building_block_id: BB1_022
  - index: 22
    codon: AAAAACCG
    building_block_id: BB1_023
  - index: 23
    codon: AAAAACCT
    building_block_id: BB1_024
  - index: 24
    codon: AAAAACGA
    building_block_id: BB1_025
  - index: 25
    codon: AAAAACGC
    building_block_id: BB1_026
  - index: 26
    codon: AAAAACGG
    building_block_id: BB1_027
  - index: 27
    codon: AAAAACGT
    building_block_id: BB1_028
  - index: 28
    codon: AAAAACTA
    building_block_id: BB1_029
  - index: 29
    codon: AAAAACTC
    building_block_id: BB1_030
  - index: 30
    codon: AAAAACTG
    building_block_id: BB1_031
  - index: 31
    codon: AAAAACTT
    building_block_id: BB1_032
  - index: 32
    codon: AAAAAGAA
    building_block_id: BB1_033
  - index: 33
    codon: AAAAAGAC
    building_block_id: BB1_034
  - index: 34
    codon: AAAAAGAG
    building_block_id: BB1_035
  - index: 35
    codon: AAAAAGAT
    building_block_id: BB1_036
  - index: 36
    codon: AAAAAGCA
    building_block_id: BB1_037
  - index: 37
    codon: AAAAAGCC
    building_block_id: BB1_038
  - index: 38
    codon: AAAAAGCG
    building_block_id: BB1_039
  - index: 39
    codon: AAAAAGCT
    building_block_id: BB1_040
  - index: 40
    codon: AAAAAGGA
    building_block_id: BB1_041
  - index: 41
    codon: AAAAAGGC
    building_block_id: BB1_042
  - index: 42
    codon: AAAAAGGG
    building_block_id: BB1_043
  - index: 43
    codon: AAAAAGGT
    building_block_id: BB1_044
  - index: 44
    codon: AAAAAGTA
    building_block_id: BB1_045
  - index: 45
    codon: AAAAAGTC
    building_block_id: BB1_046
  - index: 46
    codon: AAAAAGTG
    building_block_id: BB1_047
  - index: 47
    codon: AAAAAGTT
    building_block_id: BB1_048
  - index: 48
    codon: AAAAATAA
    building_block_id: BB1_049
  - index: 49
    codon: AAAAATAC
    building_block_id: BB1_050
  - index: 50
    codon: AAAAATAG
    building_block_id: BB1_051
  - index: 51
    codon: AAAAATAT
    building_block_id: BB1_052
  - index: 52
    codon: AAAAATCA
    building_block_id: BB1_053
  - index: 53
    codon: AAAAATCC
    building_block_id: BB1_054
  - index: 54
    codon: AAAAATCG
    building_block_id: BB1_055
  - index: 55
    codon: AAAAATCT
    building_block_id: BB1_056
  - index: 56
    codon: AAAAATGA
    building_block_id: BB1_057
  - index: 57
    codon: AAAAATGC
    building_block_id: BB1_058
  - index: 58
    codon: AAAAATGG
    building_block_id: BB1_059
  - index: 59
    codon: AAAAATGT
    building_block_id: BB1_060
  - index: 60
    codon: AAAAATTA
    building_block_id: BB1_061
  - index: 61
    codon: AAAAATTC
    building_block_id: BB1_062
  - index: 62
    codon: AAAAATTG
    building_block_id: BB1_063
  - index: 63
    codon: AAAAATTT
    building_block_id: BB1_064
  - index: 64
    codon: AAAACAAA
    building_block_id: BB1_065
  - index: 65
    codon: AAAACAAC
    building_block_id: BB1_066
  - index: 66
    codon: AAAACAAG
    building_block_id: BB1_067
  - index: 67
    codon: AAAACAAT
    building_block_id: BB1_068
  - index: 68
    codon: AAAACACA
    building_block_id: BB1_069
  - index: 69
    codon: AAAACACC
    building_block_id: BB1_070
  - index: 70
    codon: AAAACACG
    building_block_id: BB1_071
  - index: 71
    codon: AAAACACT
    building_block_id: BB1_072
  - index: 72
    codon: AAAACAGA
    building_block_id: BB1_073
  - index: 73
    codon: AAAACAGC
    building_block_id: BB1_074
  - index: 74
    codon: AAAACAGG
    building_block_id: BB1_075
  - index: 75
    codon: AAAACAGT
    building_block_id: BB1_076
  - index: 76
    codon: AAAACATA
    building_block_id: BB1_077
  - index: 77
    codon: AAAACATC
    building_block_id: BB1_078
  - index: 78
    codon: AAAACATG
    building_block_id: BB1_079
  - index: 79
    codon: AAAACATT
    building_block_id: BB1_080
  - index: 80
    codon: AAAACCAA
    building_block_id: BB1_081
  - index: 81
    codon: AAAACCAC
    building_block_id: BB1_082
  - index: 82
    codon: AAAACCAG
    building_block_id: BB1_083
  - index: 83
    codon: AAAACCAT
    building_block_id: BB1_084
  - index: 84
    codon: AAAACCCA
    building_block_id: BB1_085
  - index: 85
    codon: AAAACCCC
    building_block_id: BB1_086
  - index: 86
    codon: AAAACCCG
    building_block_id: BB1_087
  - index: 87
    codon: AAAACCCT
    building_block_id: BB1_088
  - index: 88
    codon: AAAACCGA
    building_block_id: BB1_089
  - index: 89
    codon: AAAACCGC
    building_block_id: BB1_090
  - index: 90
    codon: AAAACCGG
    building_block_id: BB1_091
  - index: 91
    codon: AAAACCGT
    building_block_id: BB1_092
  - index: 92
    codon: AAAACCTA
    building_block_id: BB1_093
  - index: 93
    codon: AAAACCTC
    building_block_id: BB1_094
  - index: 94
    codon: AAAACCTG
    building_block_id: BB1_095
  - index: 95
    codon: AAAACCTT
    building_block_id: BB1_096
  - index: 96
    codon: AAAACGAA
    building_block_id: BB1_097
  - index: 97
    codon: AAAACGAC
    building_block_id: BB1_098
  - index: 98
    codon: AAAACGAG
    building_block_id: BB1_099
  - index: 99
    codon: AAAACGAT
    building_block_id: BB1_100
  B1:
  - index: 0
    codon: AGCTACAA
    building_block_id: BB2_001
  - index: 1
    codon: AGCTACAC
    building_block_id: BB2_002
  - index: 2
    codon: AGCTACAG
    building_block_id: BB2_003
  - index: 3
    codon: AGCTACAT
    building_block_id: BB2_004
  - index: 4
    codon: AGCTACCA
    building_block_id: BB2_005
  - index: 5
    codon: AGCTACCC
    building_block_id: BB2_006
  - index: 6
    codon: AGCTACCG
    building_block_id: BB2_007
  - index: 7
    codon: AGCTACCT
    building_block_id: BB2_008
  - index: 8
    codon: AGCTACGA
    building_block_id: BB2_009
  - index: 9
    codon: AGCTACGC
    building_block_id: BB2_010
  - index: 10
    codon: AGCTACGG
    building_block_id: BB2_011
  - index: 11
    codon: AGCTACGT
    building_block_id: BB2_012
  - index: 12
    codon: AGCTACTA
    building_block_id: BB2_013
  - index: 13
    codon: AGCTACTC
    building_block_id: BB2_014
  - index: 14
    codon: AGCTACTG
    building_block_id: BB2_015
  - index: 15
    codon: AGCTACTT
    building_block_id: BB2_016
  - index: 16
    codon: AGCTAGAA
    building_block_id: BB2_017
  - index: 17
    codon: AGCTAGAC
    building_block_id: BB2_018
  - index: 18
    codon: AGCTAGAG
    building_block_id: BB2_019
  - index: 19
    codon: AGCTAGAT
    building_block_id: BB2_020
  - index: 20
    codon: AGCTAGCA
    building_block_id: BB2_021
  - index: 21
    codon: AGCTAGCC
    building_block_id: BB2_022
  - index: 22
    codon: AGCTAGCG
    building_block_id: BB2_023
  - index: 23
    codon: AGCTAGCT
    building_block_id: BB2_024
  - index: 24
    codon: AGCTAGGA
    building_block_id: BB2_025
  - index: 25
    codon: AGCTAGGC
    building_block_id: BB2_026
  - index: 26
    codon: AGCTAGGG
    building_block_id: BB2_027
  - index: 27
    codon: AGCTAGGT
    building_block_id: BB2_028
  - index: 28
    codon: AGCTAGTA
    building_block_id: BB2_029
  - index: 29
    codon: AGCTAGTC
    building_block_id: BB2_030
  - index: 30
    codon: AGCTAGTG
    building_block_id: BB2_031
  - index: 31
    codon: AGCTAGTT
    building_block_id: BB2_032
  - index: 32
    codon: AGCTATAA
    building_block_id: BB2_033
  - index: 33
    codon: AGCTATAC
    building_block_id: BB2_034
  - index: 34
    codon: AGCTATAG
    building_block_id: BB2_035
  - index: 35
    codon: AGCTATAT
    building_block_id: BB2_036
  - index: 36
    codon: AGCTATCA
    building_block_id: BB2_037
  - index: 37
    codon: AGCTATCC
    building_block_id: BB2_038
  - index: 38
    codon: AGCTATCG
    building_block_id: BB2_039
  - index: 39
    codon: AGCTATCT
    building_block_id: BB2_040
  - index: 40
    codon: AGCTATGA
    building_block_id: BB2_041
  - index: 41
    codon: AGCTATGC
    building_block_id: BB2_042
  - index: 42
    codon: AGCTATGG
    building_block_id: BB2_043
  - index: 43
    codon: AGCTATGT
    building_block_id: BB2_044
  - index: 44
    codon: AGCTATTA
    building_block_id: BB2_045
  - index: 45
    codon: AGCTATTC
    building_block_id: BB2_046
  - index: 46
    codon: AGCTATTG
    building_block_id: BB2_047
  - index: 47
    codon: AGCTATTT
    building_block_id: BB2_048
  - index: 48
    codon: AGCTCAAA
    building_block_id: BB2_049
  - index: 49
    codon: AGCTCAAC
    building_block_id: BB2_050
  - index: 50
    codon: AGCTCAAG
    building_block_id: BB2_051
  - index: 51
    codon: AGCTCAAT
    building_block_id: BB2_052
  - index: 52
    codon: AGCTCACA
    building_block_id: BB2_053
  - index: 53
    codon: AGCTCACC
    building_block_id: BB2_054
  - index: 54
    codon: AGCTCACG
    building_block_id: BB2_055
  - index: 55
    codon: AGCTCACT
    building_block_id: BB2_056
  - index: 56
    codon: AGCTCAGA
    building_block_id: BB2_057
  - index: 57
    codon: AGCTCAGC
    building_block_id: BB2_058
  - index: 58
    codon: AGCTCAGG
    building_block_id: BB2_059
  - index: 59
    codon: AGCTCAGT
    building_block_id: BB2_060
  - index: 60
    codon: AGCTCATA
    building_block_id: BB2_061
  - index: 61
    codon: AGCTCATC
    building_block_id: BB2_062
  - index: 62
    codon: AGCTCATG
    building_block_id: BB2_063
  - index: 63
    codon: AGCTCATT
    building_block_id: BB2_064
  - index: 64
    codon: AGCTCCAA
    building_block_id: BB2_065
  - index: 65
    codon: AGCTCCAC
    building_block_id: BB2_066
  - index: 66
    codon: AGCTCCAG
    building_block_id: BB2_067
  - index: 67
    codon: AGCTCCAT
    building_block_id: BB2_068
  - index: 68
    codon: AGCTCCCA
    building_block_id: BB2_069
  - index: 69
    codon: AGCTCCCC
    building_block_id: BB2_070
  - index: 70
    codon: AGCTCCCG
    building_block_id: BB2_071
  - index: 71
    codon: AGCTCCCT
    building_block_id: BB2_072
  - index: 72
    codon: AGCTCCGA
    building_block_id: BB2_073
  - index: 73
    codon: AGCTCCGC
    building_block_id: BB2_074
  - index: 74
    codon: AGCTCCGG
    building_block_id: BB2_075
  - index: 75
    codon: AGCTCCGT
    building_block_id: BB2_076
  - index: 76
    codon: AGCTCCTA
    building_block_id: BB2_077
  - index: 77
    codon: AGCTCCTC
    building_block_id: BB2_078
  - index: 78
    codon: AGCTCCTG
    building_block_id: BB2_079
  - index: 79
    codon: AGCTCCTT
    building_block_id: BB2_080
  - index: 80
    codon: AGCTCGAA
    building_block_id: BB2_081
  - index: 81
    codon: AGCTCGAC
    building_block_id: BB2_082
  - index: 82
    codon: AGCTCGAG
    building_block_id: BB2_083
  - index: 83
    codon: AGCTCGAT
    building_block_id: BB2_084
  - index: 84
    codon: AGCTCGCA
    building_block_id: BB2_085
  - index: 85
    codon: AGCTCGCC
    building_block_id: BB2_086
  - index: 86
    codon: AGCTCGCG
    building_block_id: BB2_087
  - index: 87
    codon: AGCTCGCT
    building_block_id: BB2_088
  - index: 88
    codon: AGCTCGGA
    building_block_id: BB2_089
  - index: 89
    codon: AGCTCGGC
    building_block_id: BB2_090
  - index: 90
    codon: AGCTCGGG
    building_block_id: BB2_091
  - index: 91
    codon: AGCTCGGT
    building_block_id: BB2_092
  - index: 92
    codon: AGCTCGTA
    building_block_id: BB2_093
  - index: 93
    codon: AGCTCGTC
    building_block_id: BB2_094
  - index: 94
    codon: AGCTCGTG
    building_block_id: BB2_095
  - index: 95
    codon: AGCTCGTT
    building_block_id: BB2_096
  - index: 96
    codon: AGCTCTAA
    building_block_id: BB2_097
  - index: 97
    codon: AGCTCTAC
    building_block_id: BB2_098
  - index: 98
    codon: AGCTCTAG
    building_block_id: BB2_099
  - index: 99
    codon: AGCTCTAT
    building_block_id: BB2_100
library:
  products: []
  educts: []
  reactions: []
  bb_edges: []
  other_edges: []
  building_blocks:
  - B0
  - B1
catalog:
  compounds: {}
  reactions: {}
