from __future__ import annotations

from pathlib import Path

from delt_hit.utils import read_yaml


def load_analysis_experiment(*, analysis_config: Path, name: str) -> dict:
    """Load one analysis experiment from an analysis config file."""
    cfg = read_yaml(analysis_config)
    experiments = cfg.get("experiments", [])
    matches = [exp for exp in experiments if exp.get("name") == name]
    if not matches:
        raise ValueError(f"Experiment {name} not found in analysis config {analysis_config}.")

    return matches[0]


def load_project_config(*, config_path: Path) -> dict:
    """Load a DELT-Hit project config generated by init."""
    return read_yaml(config_path)


def derive_library_size(*, project_config: dict) -> int:
    """Derive the encoded library size from project-config building block whitelists."""
    building_blocks = project_config.get("library", {}).get("building_blocks", [])
    whitelists = project_config.get("whitelists", {})

    if not building_blocks:
        raise ValueError("Project config does not define any library building blocks.")

    library_size = 1
    for building_block in building_blocks:
        entries = whitelists.get(building_block)
        if entries is None:
            raise ValueError(f"Project config is missing whitelist entries for building block {building_block}.")
        count = len(entries)
        if count <= 0:
            raise ValueError(f"Building block {building_block} has no whitelist entries, cannot derive library size.")
        library_size *= count

    if library_size <= 0:
        raise ValueError("Derived library size must be positive.")
    return library_size
