ignore_tool_compounds: true
demultiplexer_algorithm: regex
demultiplexer_mode: library
realign: false
library_error_tolerance: 0
library_error_correction_mode_str: disable
min_library_overlap: 10
revcomp: false
library_wiggle: false
wiggle: false
decode_matching_approach: first_perfect
max_read_length: 128
min_read_length: 42
default_error_correction_mode_str: disable
