experiment:
  name: synthetic_4cycle_100m_err=1_bbonly
  fastq_path: /work/FAC/FBM/DBC/mrapsoma/prometex/projects/delt-hit/benchmarks/demultiplex/data/synthetic_4cycle_100m_err=1_bbonly/synthetic_4cycle_100m_err=1_bbonly.fastq.gz
  save_dir: /work/FAC/FBM/DBC/mrapsoma/prometex/projects/delt-hit/benchmarks/demultiplex/tools/delt/synthetic_4cycle_100m_err=1_bbonly
  num_cores: 1
selections:
  synthetic_selection:
    operator: Codex
    date: '2026-04-24'
    group: synthetic
    target: synthetic_target
    S0: ACGTACGTAC
    ids:
    - 0
structure:
- name: S0
  type: selection
  max_error_rate: 0.1
  indels: false
- name: B0
  type: building_block
  max_error_rate: 0.125
  indels: false
- name: B1
  type: building_block
  max_error_rate: 0.125
  indels: false
- name: B2
  type: building_block
  max_error_rate: 0.125
  indels: false
- name: B3
  type: building_block
  max_error_rate: 0.125
  indels: false
- name: C0
  type: constant
  max_error_rate: 0.125
  indels: false
whitelists:
  C0:
  - codon: TTGGAACC
  S0:
  - name: synthetic_selection
    codon: NNNNNNNNACGTACGTAC
  B0:
  - index: 0
    codon: AAAAAAAA
    building_block_id: BB1_001
  - index: 1
    codon: AAAAACCC
    building_block_id: BB1_002
  - index: 2
    codon: AAAAAGGG
    building_block_id: BB1_003
  - index: 3
    codon: AAAAATTT
    building_block_id: BB1_004
  - index: 4
    codon: AAAACACG
    building_block_id: BB1_005
  - index: 5
    codon: AAAACCAT
    building_block_id: BB1_006
  - index: 6
    codon: AAAACGTA
    building_block_id: BB1_007
  - index: 7
    codon: AAAACTGC
    building_block_id: BB1_008
  - index: 8
    codon: AAAAGAGT
    building_block_id: BB1_009
  - index: 9
    codon: AAAAGCTG
    building_block_id: BB1_010
  B1:
  - index: 0
    codon: AGCTACAA
    building_block_id: BB2_001
  - index: 1
    codon: AGCTAGCC
    building_block_id: BB2_002
  - index: 2
    codon: AGCTATGG
    building_block_id: BB2_003
  - index: 3
    codon: AGCTCAAC
    building_block_id: BB2_004
  - index: 4
    codon: AGCTCCCG
    building_block_id: BB2_005
  - index: 5
    codon: AGCTCGGA
    building_block_id: BB2_006
  - index: 6
    codon: AGCTCTTT
    building_block_id: BB2_007
  - index: 7
    codon: AGCTGACA
    building_block_id: BB2_008
  - index: 8
    codon: AGCTGCGC
    building_block_id: BB2_009
  - index: 9
    codon: AGCTGGAG
    building_block_id: BB2_010
  B2:
  - index: 0
    codon: CATGAGAA
    building_block_id: BB3_001
  - index: 1
    codon: CATGATCC
    building_block_id: BB3_002
  - index: 2
    codon: CATGCAAC
    building_block_id: BB3_003
  - index: 3
    codon: CATGCCCA
    building_block_id: BB3_004
  - index: 4
    codon: CATGCGGG
    building_block_id: BB3_005
  - index: 5
    codon: CATGCTTT
    building_block_id: BB3_006
  - index: 6
    codon: CATGGACG
    building_block_id: BB3_007
  - index: 7
    codon: CATGGCAT
    building_block_id: BB3_008
  - index: 8
    codon: CATGGGTC
    building_block_id: BB3_009
  - index: 9
    codon: CATGGTGA
    building_block_id: BB3_010
  B3:
  - index: 0
    codon: CTCCATAA
    building_block_id: BB4_001
  - index: 1
    codon: CTCCCAAC
    building_block_id: BB4_002
  - index: 2
    codon: CTCCCCCA
    building_block_id: BB4_003
  - index: 3
    codon: CTCCCGGG
    building_block_id: BB4_004
  - index: 4
    codon: CTCCCTTT
    building_block_id: BB4_005
  - index: 5
    codon: CTCCGACG
    building_block_id: BB4_006
  - index: 6
    codon: CTCCGCAT
    building_block_id: BB4_007
  - index: 7
    codon: CTCCGGTA
    building_block_id: BB4_008
  - index: 8
    codon: CTCCGTGC
    building_block_id: BB4_009
  - index: 9
    codon: CTCCTAGA
    building_block_id: BB4_010
library:
  products: []
  educts: []
  reactions: []
  bb_edges: []
  other_edges: []
  building_blocks:
  - B0
  - B1
  - B2
  - B3
catalog:
  compounds: {}
  reactions: {}
